import { useEffect, useRef } from 'react';
import type { Engine, Snapshot } from '../game/Engine';

type Props={engine:Engine;snapshot:Snapshot;onBack:()=>void;onMenu:()=>void};
export default function GameCanvas({engine,snapshot,onBack,onMenu}:Props){
 const canvas=useRef<HTMLCanvasElement>(null), drag=useRef<{x:number;y:number}|null>(null), snapRef=useRef(snapshot);
 snapRef.current=snapshot;
 useEffect(()=>{if(snapshot.active!==1||snapshot.phase!=='aim')return;const timer=window.setTimeout(()=>engine.aiShot(),450);return()=>window.clearTimeout(timer)},[engine,snapshot.active,snapshot.phase]);
 useEffect(()=>{const c=canvas.current!;const ctx=c.getContext('2d')!;let frame=0;const draw=()=>{const snapshot=snapRef.current;const r=c.getBoundingClientRect(),d=devicePixelRatio;c.width=r.width*d;c.height=r.height*d;ctx.setTransform(d,0,0,d,0,0);engine.resize(r.width,r.height);const W=r.width,H=r.height;
  const g=ctx.createLinearGradient(0,0,W,H);g.addColorStop(0,'#b87538');g.addColorStop(.5,'#8e4b25');g.addColorStop(1,'#603017');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.fillStyle='rgba(45,18,7,.16)';for(let i=0;i<24;i++)ctx.fillRect((i*97)%W,(i*41)%H,W*.4,1);
  ctx.strokeStyle='rgba(255,226,172,.45)';ctx.lineWidth=3;ctx.strokeRect(10,10,W-20,H-20);const b=snapshot.bodies;
  for(const [i,p] of b.entries()){ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.a);ctx.shadowColor='rgba(23,8,2,.45)';ctx.shadowBlur=10;ctx.shadowOffsetY=5;ctx.fillStyle=p.spec.color;round(ctx,-p.spec.length/2,-p.spec.width/2,p.spec.length,p.spec.width,8);ctx.fill();ctx.shadowColor='transparent';ctx.fillStyle=p.spec.cap;round(ctx,p.spec.length*.31,-p.spec.width/2,p.spec.length*.19,p.spec.width,4);ctx.fill();ctx.fillStyle='rgba(255,255,255,.35)';ctx.fillRect(-p.spec.length*.28,-p.spec.width*.26,p.spec.length*.38,2);ctx.fillStyle=i===0?'#f7d047':'#cae8ff';ctx.beginPath();ctx.arc(-p.spec.length*.28,0,3,0,7);ctx.fill();ctx.restore();if(!p.alive){ctx.fillStyle='rgba(33,12,4,.5)';ctx.fillRect(0,0,W,H)}}
  if(drag.current&&snapshot.phase==='aim'&&snapshot.active===0){const p=b[0],dx=drag.current.x-p.x,dy=drag.current.y-p.y,L=Math.min(150,Math.hypot(dx,dy));ctx.save();ctx.strokeStyle=L>100?'#ffcf51':'#b9f18b';ctx.lineWidth=4;ctx.setLineDash([8,7]);ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(p.x+dx/Math.hypot(dx,dy)*L,p.y+dy/Math.hypot(dx,dy)*L);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='rgba(20,15,8,.65)';round(ctx,p.x+18,p.y-46,102,26,13);ctx.fill();ctx.fillStyle='#fff5d6';ctx.font='600 12px system-ui';ctx.fillText(`POWER ${Math.round(Math.min(100,L/1.5))}%`,p.x+29,p.y-29);ctx.restore()} frame=requestAnimationFrame(draw)};frame=requestAnimationFrame(draw);return()=>cancelAnimationFrame(frame)},[engine]);
 const point=(e:React.PointerEvent)=>{const r=canvas.current!.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}};
 const down=(e:React.PointerEvent)=>{if(snapshot.phase!=='aim'||snapshot.active!==0)return;const p=point(e),b=snapshot.bodies[0];if(Math.hypot(p.x-b.x,p.y-b.y)<85){drag.current=p;canvas.current?.setPointerCapture(e.pointerId)}};
 const move=(e:React.PointerEvent)=>{if(!drag.current)return;drag.current=point(e);const b=snapshot.bodies[0];engine.aim(Math.min(100,Math.hypot(drag.current.x-b.x,drag.current.y-b.y)/1.5))};
 const up=()=>{if(!drag.current)return;const b=snapshot.bodies[0],p=drag.current;drag.current=null;engine.flick(p.x-b.x,p.y-b.y)};
 return <div className="game-shell"><header><button className="icon" onClick={onBack}>←</button><div className="brand-small">PEN FIGHT <span>LAST BENCH</span></div><button className="icon" onClick={onMenu}>⌂</button></header><section className="score"><div className={snapshot.active===0?'active':''}><small>PLAYER ONE</small><strong>{snapshot.scores[0]}</strong><i>{[0,1,2].map(n=><b key={n} className={n<snapshot.scores[0]?'won':''}/>)}</i></div><div className="round"><small>ROUND {snapshot.round}</small><b>BEST OF 5</b></div><div className={snapshot.active===1?'active':''}><small>{snapshot.active===1?'OPPONENT':'PLAYER TWO'}</small><strong>{snapshot.scores[1]}</strong><i>{[0,1,2].map(n=><b key={n} className={n<snapshot.scores[1]?'won blue':''}/>)}</i></div></section><canvas ref={canvas} onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={up}/><div className="turn-card"><span className={snapshot.phase==='moving'?'pulse':''}>{snapshot.phase==='aim'?'◉':'✦'}</span><div><b>{snapshot.message}</b><small>{snapshot.active===0&&snapshot.phase==='aim'?'Drag away from your pen to build power':'Wait for the pens to settle'}</small></div></div></div>
}
function round(c:CanvasRenderingContext2D,x:number,y:number,w:number,h:number,r:number){c.beginPath();c.roundRect(x,y,w,h,r)}
