import { useEffect, useRef, useState } from 'react';
import GameCanvas from './components/GameCanvas';
import { Engine, type Snapshot } from './game/Engine';
import { PENS, type PenSpec } from './game/pens';

type View='menu'|'select'|'game'|'stats';
const empty:Snapshot={bodies:[],active:0,phase:'aim',message:'',power:0,scores:[0,0],round:1};
export default function App(){const [view,setView]=useState<View>('menu'),[mine,setMine]=useState<PenSpec>(PENS[0]),[theirs,setTheirs]=useState<PenSpec>(PENS[2]),[snap,setSnap]=useState<Snapshot>(empty);const engine=useRef<Engine | null>(null);if(!engine.current)engine.current=new Engine(setSnap);const game=engine.current;useEffect(()=>{if(view==='game')game.start(mine,theirs)},[view,mine,theirs,game]);
 if(view==='game')return <GameCanvas engine={game} snapshot={snap} onBack={()=>setView('select')} onMenu={()=>setView('menu')}/>;
 if(view==='stats')return <main className="menu"><button className="back" onClick={()=>setView('menu')}>← Back</button><h1>YOUR <em>NOTEBOOK</em></h1><div className="stats"><article><b>0</b><span>Matches played</span></article><article><b>0</b><span>Knockouts</span></article><article><b>—</b><span>Win streak</span></article></div><p className="note">Your last-bench record will be saved on this device.</p></main>;
 if(view==='select')return <main className="menu select"><button className="back" onClick={()=>setView('menu')}>← Back</button><p className="eyebrow">PEN BOX</p><h1>CHOOSE YOUR <em>WEAPON</em></h1><p className="sub">Every pen has a different feel. Pick yours, then pick your rival.</p><div className="pen-grid">{PENS.map(p=><button className={'pen-card '+(mine.id===p.id?'selected':'')} onClick={()=>setMine(p)} key={p.id}><span style={{background:p.color}} className="mini-pen"/><b>{p.name}</b><small>POWER {'█'.repeat(p.stats[0])}</small><small>CONTROL {'█'.repeat(p.stats[1])}</small></button>)}</div><button className="primary" onClick={()=>setView('game')}>START THE DUEL <span>→</span></button></main>;
 return <main className="menu home"><div className="scribble">✦ since recess ✦</div><p className="eyebrow">THE ORIGINAL DESK-TOP DUEL</p><h1>PEN <em>FIGHT</em></h1><p className="tagline">The last bench game.<br/>Take your shot. Don’t fall off.</p><div className="hero-pens"><span className="pen one"/><span className="pen two"/></div><nav><button className="primary" onClick={()=>setView('select')}>QUICK DUEL <span>→</span></button><button onClick={()=>setView('select')}>LOCAL 2 PLAYER</button><button onClick={()=>setView('select')}>PRACTICE</button><button onClick={()=>setView('stats')}>YOUR NOTEBOOK</button></nav><footer>✎ Built for the back bench &nbsp; • &nbsp; sound off</footer></main>}
